name: SST Preview Deployments

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - run: npm ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.STAGING_AWS_REGION }}
      - name: Install SST
        run: |
          curl -fsSL https://ion.sst.dev/install | bash
      - name: Deploy preview
        run: npx sst deploy --stage pr-${{ github.event.number }}
        env:
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          AUTH_JWT_SECRET: ${{ secrets.AUTH_JWT_SECRET }}
      - name: Comment preview URL
        uses: actions/github-script@v7
        env:
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
        with:
          script: |
            const pr = context.issue.number;
            const url = `https://pr-${pr}-nx-sst-next.${process.env.DOMAIN_NAME}`;
            const body = `Preview environment available: ${url}`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: pr,
              body,
            });

  destroy:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - run: npm ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.STAGING_AWS_REGION }}
      - name: Install SST
        run: |
          curl -fsSL https://ion.sst.dev/install | bash
      - name: Remove preview
        run: npx sst remove --stage pr-${{ github.event.number }}
        env:
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          AUTH_JWT_SECRET: ${{ secrets.AUTH_JWT_SECRET }}
